name: BadlandsCaves
version: ${project.version}
main: me.fullpotato.badlandscaves.BadlandsCaves
api-version: 1.13
commands:
  thirst:
    usage: /thirst <get|set> <username> <value>
    description: Read or write Thirst values of Players.
  toxicity:
    usage: /toxicity <get|set> <username> <value>
    description: Read or write Toxicity values of Players.
    aliases: tox
  deaths:
    usage: /deaths <get|set> <username> <value>
    description: Read or write Death values of Players.
    aliases: death
  hardmode:
    usage: /hardmode <get|set> <value>
    description: Read or write whether or not the world is in Hardmode.
    aliases: hm
  mana:
    usage: /mana <get|set> <username> <value>
    description: Read or write Mana values of Players.
  powers:
    usage: /powers <get|set> <username> <entry> <value>
    description: Read or write Supernatural powers of Players.
    aliases:
      - supernatural
      - magic
  customitem:
    usage: /customitem <player> [amount]
    description: Give Custom Items to Players
    aliases:
      - givecustomitem
  chaos:
    usage: /chaos <get|set> <amount>
    description: Read or write chaos value of world.
  guide:
    usage: /guide
    description: Get guide book.
  craftguide:
    usage: /craftguide
    description: Open Crafting Guide
    aliases:
      - crafthelp
      - craftinghelp
      - helpcraft
      - helpcrafting
      - craftingguide
  backrooms:
    usage: /backrooms <get|enter|leave> [player] [type]
    description: Read if player is in Backrooms, force them to enter, or force to leave.
    aliases:
      - backroom
      - darkrooms
      - darkroom