package me.fullpotato.badlandscaves.CustomItems.Using.Starlight.Nebulites;

import me.fullpotato.badlandscaves.CustomItems.CustomItem;

import javax.annotation.Nullable;

public enum Nebulite {
    ENERGY_STORAGE(CustomItem.NEBULITE_ENERGY_STORAGE, null, CustomItem.STARLIGHT_HELMET, CustomItem.STARLIGHT_CHESTPLATE, CustomItem.STARLIGHT_LEGGINGS, CustomItem.STARLIGHT_BOOTS, CustomItem.STARLIGHT_SABER, CustomItem.STARLIGHT_BLASTER, CustomItem.STARLIGHT_SHIELD, CustomItem.STARLIGHT_PAXEL, CustomItem.STARLIGHT_SENTRY),
    CORRODING_LIGHTS(CustomItem.NEBULITE_CORRODING_LIGHTS, new CustomItem[]{CustomItem.NEBULITE_JAGGED_LIGHTS}, CustomItem.STARLIGHT_SABER),
    JAGGED_LIGHTS(CustomItem.NEBULITE_JAGGED_LIGHTS, new CustomItem[]{CustomItem.NEBULITE_CORRODING_LIGHTS}, CustomItem.STARLIGHT_SABER),
    FLURRYING_SWINGS(CustomItem.NEBULITE_FLURRYING_SWINGS, new CustomItem[]{CustomItem.NEBULITE_ARDENT_SLASH}, CustomItem.STARLIGHT_SABER),
    ARDENT_SLASH(CustomItem.NEBULITE_ARDENT_SLASH, new CustomItem[]{CustomItem.NEBULITE_FLURRYING_SWINGS}, CustomItem.STARLIGHT_SABER),
    WIDE_SWING(CustomItem.NEBULITE_WIDE_SWING, null, CustomItem.STARLIGHT_SABER),
    REINFORCED_PLATING(CustomItem.NEBULITE_REINFORCED_PLATING, null, CustomItem.STARLIGHT_HELMET, CustomItem.STARLIGHT_CHESTPLATE, CustomItem.STARLIGHT_LEGGINGS, CustomItem.STARLIGHT_BOOTS),
    POWER_STANCE(CustomItem.NEBULITE_POWER_STANCE, null, CustomItem.STARLIGHT_HELMET, CustomItem.STARLIGHT_CHESTPLATE, CustomItem.STARLIGHT_LEGGINGS, CustomItem.STARLIGHT_BOOTS),
    THRUSTER(CustomItem.NEBULITE_THRUSTER, null, CustomItem.STARLIGHT_HELMET, CustomItem.STARLIGHT_CHESTPLATE, CustomItem.STARLIGHT_LEGGINGS, CustomItem.STARLIGHT_BOOTS),
    OXYGENATOR(CustomItem.NEBULITE_OXYGENATOR, null, CustomItem.STARLIGHT_HELMET),
    SMOLDERING_FLAMES(CustomItem.NEBULITE_SMOLDERING_FLAMES, null, CustomItem.STARLIGHT_CHESTPLATE, CustomItem.STARLIGHT_LEGGINGS),
    TOXIN_EXPELLER(CustomItem.NEBULITE_TOXIN_EXPELLER, null, CustomItem.STARLIGHT_CHESTPLATE, CustomItem.STARLIGHT_LEGGINGS),
    SHOCK_ABSORBER(CustomItem.NEBULITE_SHOCK_ABSORBER, null, CustomItem.STARLIGHT_BOOTS),
    FORCEFIELD(CustomItem.NEBULITE_FORCEFIELD, null, CustomItem.STARLIGHT_HELMET, CustomItem.STARLIGHT_CHESTPLATE, CustomItem.STARLIGHT_LEGGINGS, CustomItem.STARLIGHT_BOOTS),
    STARLIGHT_GUARDIAN(CustomItem.NEBULITE_STARLIGHT_GUARDIAN, null, CustomItem.STARLIGHT_HELMET, CustomItem.STARLIGHT_CHESTPLATE, CustomItem.STARLIGHT_LEGGINGS, CustomItem.STARLIGHT_BOOTS),
    RAPID_FIRE(CustomItem.NEBULITE_RAPID_FIRE, null, CustomItem.STARLIGHT_BLASTER),
    SCATTERING_LIGHTS(CustomItem.NEBULITE_SCATTERING_LIGHTS, new CustomItem[]{CustomItem.NEBULITE_PENETRATING_BEAM, CustomItem.NEBULITE_HUNTERS_EYES}, CustomItem.STARLIGHT_BLASTER),
    PENETRATING_BEAM(CustomItem.NEBULITE_PENETRATING_BEAM, new CustomItem[]{CustomItem.NEBULITE_SCATTERING_LIGHTS, CustomItem.NEBULITE_HUNTERS_EYES}, CustomItem.STARLIGHT_BLASTER),
    HUNTERS_EYES(CustomItem.NEBULITE_HUNTERS_EYES, new CustomItem[]{CustomItem.NEBULITE_PENETRATING_BEAM, CustomItem.NEBULITE_SCATTERING_LIGHTS, CustomItem.NEBULITE_SUPERHEATING_LASER}, CustomItem.STARLIGHT_BLASTER),
    SUPERHEATING_LASER(CustomItem.NEBULITE_SUPERHEATING_LASER, new CustomItem[]{CustomItem.NEBULITE_HUNTERS_EYES}, CustomItem.STARLIGHT_BLASTER),
    SUPERSONIC_PROPULSORS(CustomItem.NEBULITE_SUPERSONIC_PROPULSORS, new CustomItem[]{CustomItem.NEBULITE_STARLIGHT_HAMMER}, CustomItem.STARLIGHT_PAXEL),
    DISASSEMBLER(CustomItem.NEBULITE_DISASSEMBLER, null, CustomItem.STARLIGHT_PAXEL),
    STARLIGHT_HAMMER(CustomItem.NEBULITE_STARLIGHT_HAMMER, new CustomItem[]{CustomItem.NEBULITE_RICOCHET, CustomItem.NEBULITE_SUPERSONIC_PROPULSORS}, CustomItem.STARLIGHT_PAXEL),
    RICOCHET(CustomItem.NEBULITE_RICOCHET, new CustomItem[]{CustomItem.NEBULITE_STARLIGHT_HAMMER}, CustomItem.STARLIGHT_PAXEL),
    // HARDENED_DEFENSE(CustomItem.NEBULITE_HARDENED_DEFENSE, null, CustomItem.STARLIGHT_SHIELD),
    REFLECTOR(CustomItem.NEBULITE_REFLECTOR, new CustomItem[]{CustomItem.NEBULITE_ENERGY_CONVERTER}, CustomItem.STARLIGHT_SHIELD),
    ENERGY_CONVERTER(CustomItem.NEBULITE_ENERGY_CONVERTER, new CustomItem[]{CustomItem.NEBULITE_REFLECTOR}, CustomItem.STARLIGHT_SHIELD),
    PROPULSION_BASH(CustomItem.NEBULITE_PROPULSION_BASH, null, CustomItem.STARLIGHT_SHIELD),
    COUNTERATTACK(CustomItem.NEBULITE_COUNTERATTACK, null, CustomItem.STARLIGHT_SHIELD),
    SHIELD_THRUSTER(CustomItem.NEBULITE_SHIELD_THRUSTER, null, CustomItem.STARLIGHT_SHIELD);


    private final CustomItem nebuliteItem;
    private final CustomItem[] mutuallyExplicit;
    private final CustomItem[] baseItems;
    Nebulite (CustomItem nebuliteItem, @Nullable CustomItem[] mutuallyExplicit, CustomItem... baseItems) {
        this.nebuliteItem = nebuliteItem;
        this.mutuallyExplicit = mutuallyExplicit;
        this.baseItems = baseItems;
    }

    public CustomItem getNebuliteItem() {
        return nebuliteItem;
    }

    public CustomItem[] getBaseItems() {
        return baseItems;
    }

    public CustomItem[] getMutuallyExplicit() {
        return mutuallyExplicit;
    }
}
